/**
 * Mirrors EXPENSE_TABLE_REGISTRY in Backend/src/controllers/adminController.ts.
 * Column `dataIndex`s must match exactly what GET /admin/expense-table/:tableKey
 * returns for that table (snake_case for raw tables, camelCase for Prisma
 * tables, fixed aliases for `hierarchy`). Keep the two in sync by hand.
 */

export interface ExpenseTableColumnConfig {
  dataIndex: string;
  title: string;
  width?: number;
  type?: 'date' | 'boolean';
  align?: 'left' | 'right' | 'center';
  /** Defaults to true. Set false for ids/timestamps and fields owned by another
   * workflow (e.g. fabric/body article data's own approval/SAP-sync fields). */
  editable?: boolean;
  /** Render the add/edit form field as a dropdown of this column's distinct
   * existing values (fetched from the server) instead of free text — for a
   * column whose values are really a fixed taxonomy (e.g. Attribute Name,
   * Sub Division, Major Category, Segment Type), so a new row can't drift
   * from it with a typo or a near-duplicate spelling. */
  pickFromExisting?: boolean;
  /** On the add/edit form, auto-fill this field from another column's value
   * once a 1:1 mapping between them is fetched from the server (e.g. Size
   * Master: picking a Major Category fills in its Sub Division) — a
   * convenience default, not a lock; the field stays editable afterward.
   * Names the OTHER column's `dataIndex` to watch. */
  autoFillFrom?: string;
}

export interface ExpenseTableConfig {
  title: string;
  description: string;
  rowKey: string;
  defaultSortBy: string;
  defaultSortDir: 'asc' | 'desc';
  columns: ExpenseTableColumnConfig[];
  /** Show the "Add Row" button. Must match the registry entry's `allowCreate`,
   * which is what the server actually enforces. */
  allowCreate?: boolean;
  /** Show the per-row delete button. Must match the registry's `allowDelete`. */
  allowDelete?: boolean;
  /** Editable column dataIndexes that must be filled in on the Add Row form. */
  requiredOnCreate?: string[];
}

export const EXPENSE_TABLE_CONFIGS: Record<string, ExpenseTableConfig> = {
  'major-category-grid': {
    title: 'Major Category Grid (Dropdown Values)',
    description: 'All rows currently stored in maj_cat_grid_values.',
    rowKey: 'id',
    defaultSortBy: 'id',
    defaultSortDir: 'desc',
    allowCreate: true,
    allowDelete: true,
    requiredOnCreate: ['major_category', 'attribute_name', 'value'],
    columns: [
      { dataIndex: 'id', title: 'ID', width: 80, editable: false },
      { dataIndex: 'major_category', title: 'Major Category', pickFromExisting: true },
      { dataIndex: 'attribute_name', title: 'Attribute Name', pickFromExisting: true },
      { dataIndex: 'value', title: 'Value' },
      { dataIndex: 'uploaded_at', title: 'Uploaded At', type: 'date', editable: false },
    ],
  },
  'size-master': {
    title: 'Size Master (Sizes per Major Category)',
    description: 'All rows currently stored in maj_cat_sizes.',
    rowKey: 'id',
    defaultSortBy: 'id',
    defaultSortDir: 'desc',
    allowCreate: true,
    allowDelete: true,
    requiredOnCreate: ['division', 'sub_division', 'major_category', 'size'],
    columns: [
      { dataIndex: 'id', title: 'ID', width: 80, editable: false },
      { dataIndex: 'division', title: 'Division', pickFromExisting: true },
      { dataIndex: 'major_category', title: 'Major Category', pickFromExisting: true },
      // Picking a Major Category fills this in automatically (see
      // autoFillFrom) — it's still a normal editable field afterward.
      { dataIndex: 'sub_division', title: 'Sub Division', pickFromExisting: true, autoFillFrom: 'major_category' },
      { dataIndex: 'mc_code', title: 'MC Code' },
      { dataIndex: 'size', title: 'Size' },
      { dataIndex: 'status', title: 'Status' },
      { dataIndex: 'created_at', title: 'Created At', type: 'date', editable: false },
    ],
  },
  'color-master': {
    title: 'Color Master (Father / Child Colours)',
    description: 'All rows currently stored in color_master.',
    rowKey: 'id',
    defaultSortBy: 'id',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', width: 80, editable: false },
      { dataIndex: 'father_color', title: 'Father Color' },
      { dataIndex: 'child_color', title: 'Child Color' },
      { dataIndex: 'sap_create_old', title: 'SAP Code' },
    ],
  },
  'mandatory-grid': {
    title: 'Mandatory Grid (Field Visibility per Major Category)',
    description: 'All rows currently stored in maj_cat_mandatory_grid.',
    rowKey: 'id',
    defaultSortBy: 'id',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', width: 80, editable: false },
      { dataIndex: 'major_category', title: 'Major Category' },
      { dataIndex: 'div', title: 'Division' },
      { dataIndex: 'sub_div', title: 'Sub Division' },
      { dataIndex: 'sap_key', title: 'SAP Key' },
      { dataIndex: 'label', title: 'Label' },
      { dataIndex: 'is_active', title: 'Active', type: 'boolean' },
      { dataIndex: 'uploaded_at', title: 'Uploaded At', type: 'date', editable: false },
    ],
  },
  'segment-master': {
    title: 'Segment Master (Price Segments per Major Category)',
    description: 'All rows currently stored in maj_cat_segment.',
    rowKey: 'id',
    defaultSortBy: 'id',
    defaultSortDir: 'desc',
    allowCreate: true,
    allowDelete: true,
    requiredOnCreate: ['sub_division', 'major_category', 'segment_type'],
    columns: [
      { dataIndex: 'id', title: 'ID', width: 80, editable: false },
      { dataIndex: 'sub_division', title: 'Sub Division', pickFromExisting: true },
      { dataIndex: 'major_category', title: 'Major Category', pickFromExisting: true },
      { dataIndex: 'segment_type', title: 'Segment Type', pickFromExisting: true },
      { dataIndex: 'min', title: 'Min' },
      { dataIndex: 'max', title: 'Max' },
      { dataIndex: 'created_at', title: 'Created At', type: 'date', editable: false },
      { dataIndex: 'updated_at', title: 'Updated At', type: 'date', editable: false },
    ],
  },
  'fabric-article-data': {
    title: 'Fabric Article Data (Bulk Insert)',
    description: 'All rows currently stored in fabric_article_data.',
    rowKey: 'id',
    defaultSortBy: 'createdAt',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', editable: false },
      { dataIndex: 'fabricArticleNumber', title: 'Fabric Article No.' },
      { dataIndex: 'fabricArticleDescription', title: 'Description' },
      { dataIndex: 'division', title: 'Division' },
      { dataIndex: 'subDivision', title: 'Sub Division' },
      { dataIndex: 'majorCategory', title: 'Major Category' },
      { dataIndex: 'vendorName', title: 'Vendor Name' },
      { dataIndex: 'vendorCode', title: 'Vendor Code' },
      { dataIndex: 'mFabDiv', title: 'Fab Div' },
      { dataIndex: 'mYarn', title: 'Yarn' },
      { dataIndex: 'mFabMainMvgr1', title: 'Fab Main MVGR 1' },
      { dataIndex: 'mFabMainMvgr2', title: 'Fab Main MVGR 2' },
      { dataIndex: 'mConstruction', title: 'Construction' },
      { dataIndex: 'mOunz', title: 'Ounz' },
      { dataIndex: 'mWidth', title: 'Width' },
      { dataIndex: 'mWeave01', title: 'Weave 1' },
      { dataIndex: 'mWeave02', title: 'Weave 2' },
      { dataIndex: 'mCount', title: 'Count' },
      { dataIndex: 'mComposition', title: 'Composition' },
      { dataIndex: 'mFinish', title: 'Finish' },
      { dataIndex: 'mGsm', title: 'GSM' },
      { dataIndex: 'mLycra', title: 'Lycra' },
      { dataIndex: 'approvalStatus', title: 'Approval Status', editable: false },
      { dataIndex: 'approvedAt', title: 'Approved At', type: 'date', editable: false },
      { dataIndex: 'approvedBy', title: 'Approved By (User ID)', editable: false },
      { dataIndex: 'sapSyncStatus', title: 'SAP Sync Status', editable: false },
      { dataIndex: 'sapSyncMessage', title: 'SAP Sync Message', editable: false },
      { dataIndex: 'userName', title: 'Uploaded By', editable: false },
      { dataIndex: 'createdAt', title: 'Created At', type: 'date', editable: false },
      { dataIndex: 'updatedAt', title: 'Updated At', type: 'date', editable: false },
    ],
  },
  'fabric-article-master': {
    title: 'Fabric Article Master (Fabric Hierarchy)',
    description: 'All rows currently stored in fabric_article_master.',
    rowKey: 'id',
    defaultSortBy: 'createdAt',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', editable: false },
      { dataIndex: 'seg', title: 'Segment' },
      { dataIndex: 'div', title: 'Division' },
      { dataIndex: 'subDiv', title: 'Sub Division' },
      { dataIndex: 'majCat', title: 'Major Category' },
      { dataIndex: 'mcCode', title: 'MC Code' },
      { dataIndex: 'mcDes', title: 'MC Description' },
      { dataIndex: 'status', title: 'Status' },
      { dataIndex: 'hsnCd', title: 'HSN Code' },
      { dataIndex: 'artType', title: 'Article Type' },
      { dataIndex: 'createdAt', title: 'Created At', type: 'date', editable: false },
      { dataIndex: 'updatedAt', title: 'Updated At', type: 'date', editable: false },
    ],
  },
  'national-grid': {
    title: 'National Grid (Attribute Values)',
    description: 'All rows currently stored in national_grid_master.',
    rowKey: 'id',
    defaultSortBy: 'createdAt',
    defaultSortDir: 'desc',
    allowCreate: true,
    allowDelete: true,
    requiredOnCreate: ['attributeName', 'code'],
    columns: [
      { dataIndex: 'id', title: 'ID', editable: false },
      { dataIndex: 'attributeName', title: 'Attribute Name', pickFromExisting: true },
      { dataIndex: 'code', title: 'Code' },
      { dataIndex: 'fullForm', title: 'Full Form' },
      { dataIndex: 'isActive', title: 'Active', type: 'boolean' },
      { dataIndex: 'createdAt', title: 'Created At', type: 'date', editable: false },
    ],
  },
  hierarchy: {
    title: 'Hierarchy (Division / Sub-Division / Major Category)',
    description: 'Flattened view of departments → sub_departments → categories. Editing here only changes a category’s own fields, not the tree structure.',
    rowKey: 'major_category_code',
    defaultSortBy: 'division',
    defaultSortDir: 'asc',
    columns: [
      { dataIndex: 'division_code', title: 'Division Code', editable: false },
      { dataIndex: 'division', title: 'Division', editable: false },
      { dataIndex: 'sub_division_code', title: 'Sub Division Code', editable: false },
      { dataIndex: 'sub_division', title: 'Sub Division', editable: false },
      { dataIndex: 'major_category_code', title: 'Major Category Code', editable: false },
      { dataIndex: 'major_category', title: 'Major Category' },
      { dataIndex: 'full_form', title: 'Full Form' },
      { dataIndex: 'description', title: 'Description' },
      { dataIndex: 'mc_code', title: 'MC Code' },
      { dataIndex: 'mc_des', title: 'MC Description' },
      { dataIndex: 'fabric_division', title: 'Fabric Division' },
      { dataIndex: 'garment_type', title: 'Garment Type', editable: false },
      { dataIndex: 'display_order', title: 'Display Order' },
      { dataIndex: 'is_active', title: 'Active', type: 'boolean' },
      { dataIndex: 'created_at', title: 'Created At', type: 'date', editable: false },
      { dataIndex: 'updated_at', title: 'Updated At', type: 'date', editable: false },
    ],
  },
  'broader-menu': {
    title: 'Broader Menu (Merchandising Master)',
    description:
      'All rows currently stored in broader_menu — one per MC CD, from the BM-H sheet of the Broader Menu workbook.',
    rowKey: 'id',
    defaultSortBy: 'mcCd',
    defaultSortDir: 'asc',
    allowCreate: true,
    allowDelete: true,
    requiredOnCreate: ['mcCd', 'mcDesc'],
    columns: [
      { dataIndex: 'id', title: 'ID', width: 70, editable: false },
      { dataIndex: 'sn', title: 'SN', width: 70, align: 'right' },
      { dataIndex: 'mcCd', title: 'MC CD', width: 110, align: 'right' },
      { dataIndex: 'seg', title: 'Segment', width: 90 },
      { dataIndex: 'div', title: 'Division', width: 100 },
      { dataIndex: 'subDiv', title: 'Sub Division', width: 110 },
      { dataIndex: 'majCatCd', title: 'Maj Cat Code', width: 110, align: 'right' },
      { dataIndex: 'majCatNm', title: 'Major Category', width: 180 },
      { dataIndex: 'subCatCd', title: 'Sub Cat Code', width: 110, align: 'right' },
      { dataIndex: 'subCatDesc', title: 'Sub Category', width: 180 },
      { dataIndex: 'mcDesc', title: 'MC Description', width: 200 },
      { dataIndex: 'ssn', title: 'Season', width: 80 },
      { dataIndex: 'mcStat', title: 'MC Status', width: 100 },
      { dataIndex: 'subCatStat', title: 'Sub Cat Status', width: 120 },
      { dataIndex: 'majCatStat', title: 'Maj Cat Status', width: 120 },
      { dataIndex: 'sizeApplicable', title: 'Size Applicable', width: 120 },
      { dataIndex: 'divStat', title: 'Division Status', width: 120 },
      { dataIndex: 'mcPkSz', title: 'MC Pack Size', width: 110, align: 'right' },
      { dataIndex: 'subCatPkSz', title: 'Sub Cat Pack Size', width: 130, align: 'right' },
      { dataIndex: 'noOfOptions', title: 'No. of Options', width: 120, align: 'right' },
      { dataIndex: 'avgDensity', title: 'Avg Density', width: 110, align: 'right' },
      { dataIndex: 'accDensity', title: 'Acc Density', width: 110, align: 'right' },
      { dataIndex: 'wgDensity', title: 'WG/7FT Density', width: 130, align: 'right' },
      { dataIndex: 'fg46FtDensity', title: 'FG-4.6FT Density', width: 140, align: 'right' },
      { dataIndex: 'fg5FtDensity', title: 'FG-5FT Density', width: 130, align: 'right' },
      { dataIndex: 'fg4ADensity', title: 'FG-4A Density', width: 130, align: 'right' },
      { dataIndex: 'fg8ADensity', title: 'FG-8A Density', width: 130, align: 'right' },
      { dataIndex: 'acp', title: 'ACP', width: 90, align: 'right' },
      { dataIndex: 'oldDensity', title: 'Old Density', width: 110, align: 'right' },
      { dataIndex: 'seq', title: 'Seq', width: 80, align: 'right' },
      { dataIndex: 'mjCatTyp', title: 'Maj Cat Type', width: 110 },
      { dataIndex: 'fixtr', title: 'Fixture', width: 100 },
      { dataIndex: 'newMcCd', title: 'New MC CD', width: 110, align: 'right' },
      { dataIndex: 'newMcDesc', title: 'New MC Description', width: 180 },
      { dataIndex: 'oldMcDesc', title: 'Old MC Description', width: 180 },
      { dataIndex: 'oldSubCatCd', title: 'Old Sub Cat Code', width: 130, align: 'right' },
      { dataIndex: 'oldSubCatDesc', title: 'Old Sub Category', width: 170 },
      { dataIndex: 'legacyMcDesc', title: 'Legacy MC Description', width: 190 },
      { dataIndex: 'effectiveDate', title: 'Effective Date', width: 130, type: 'date' },
      { dataIndex: 'remarks', title: 'Remarks', width: 180 },
      { dataIndex: 'gmStatus', title: 'GM Status', width: 110 },
      { dataIndex: 'currentMcStatus', title: 'Current MC Status', width: 150 },
      { dataIndex: 'fullMcName', title: 'Full MC Name', width: 190 },
      { dataIndex: 'winterStatus', title: 'Winter Status', width: 120 },
      { dataIndex: 'uploadedAt', title: 'Uploaded At', width: 160, type: 'date', editable: false },
      { dataIndex: 'updatedAt', title: 'Updated At', width: 160, type: 'date', editable: false },
    ],
  },
  'body-article-data': {
    title: 'Body Article Data (Bulk Update)',
    description: 'All rows currently stored in body_article_data.',
    rowKey: 'id',
    defaultSortBy: 'createdAt',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', editable: false },
      { dataIndex: 'bodyArticleNumber', title: 'Body Article No.' },
      { dataIndex: 'bodyArticleDescription', title: 'Description' },
      { dataIndex: 'division', title: 'Division' },
      { dataIndex: 'subDivision', title: 'Sub Division' },
      { dataIndex: 'majorCategory', title: 'Major Category' },
      { dataIndex: 'mcCode', title: 'MC Code' },
      { dataIndex: 'articleNumber', title: 'Article Number' },
      { dataIndex: 'flatId', title: 'Flat ID', editable: false },
      { dataIndex: 'vendorName', title: 'Vendor Name' },
      { dataIndex: 'vendorCode', title: 'Vendor Code' },
      { dataIndex: 'season', title: 'Season' },
      { dataIndex: 'year', title: 'Year' },
      { dataIndex: 'hsnTaxCode', title: 'HSN Tax Code' },
      { dataIndex: 'mCollarType', title: 'Collar Type' },
      { dataIndex: 'mCollarStyle', title: 'Collar Style' },
      { dataIndex: 'mNeckType', title: 'Neck Type' },
      { dataIndex: 'mNeckStyle', title: 'Neck Style' },
      { dataIndex: 'mPlacket', title: 'Placket' },
      { dataIndex: 'mBltType', title: 'Belt Type' },
      { dataIndex: 'mBltStyle', title: 'Belt Style' },
      { dataIndex: 'mSleevesMainStyle', title: 'Sleeves Main Style' },
      { dataIndex: 'mSleeveFold', title: 'Sleeve Fold' },
      { dataIndex: 'mBtmFold', title: 'Bottom Fold' },
      { dataIndex: 'mNoOfPocket', title: 'No. of Pockets' },
      { dataIndex: 'mPocket', title: 'Pocket' },
      { dataIndex: 'mExtraPocket', title: 'Extra Pocket' },
      { dataIndex: 'mFit', title: 'Fit' },
      { dataIndex: 'mBodyStyle', title: 'Body Style' },
      { dataIndex: 'mLength', title: 'Length' },
      { dataIndex: 'mSet', title: 'Set' },
      { dataIndex: 'cmtpCost', title: 'CMTP Cost', align: 'right' },
      { dataIndex: 'cmpCost', title: 'CMP Cost', align: 'right' },
      { dataIndex: 'fabCost', title: 'Fab Cost', align: 'right' },
      { dataIndex: 'fabCons', title: 'Fab Cons', align: 'right' },
      { dataIndex: 'width', title: 'Width', align: 'right' },
      { dataIndex: 'approvalStatus', title: 'Approval Status', editable: false },
      { dataIndex: 'approvedAt', title: 'Approved At', type: 'date', editable: false },
      { dataIndex: 'approvedBy', title: 'Approved By (User ID)', editable: false },
      { dataIndex: 'sapSyncStatus', title: 'SAP Sync Status', editable: false },
      { dataIndex: 'sapSyncMessage', title: 'SAP Sync Message', editable: false },
      { dataIndex: 'userName', title: 'Uploaded By', editable: false },
      { dataIndex: 'createdAt', title: 'Created At', type: 'date', editable: false },
      { dataIndex: 'updatedAt', title: 'Updated At', type: 'date', editable: false },
    ],
  },
  'raw-articles': {
    title: 'Raw Articles (SRM Pipeline)',
    description:
      'All rows currently stored in raw_articles. Read-only — this is a sync-pipeline staging table, so edits here would just be overwritten by the next sync. (The internal extracted_data JSON blob is omitted here.)',
    rowKey: 'id',
    defaultSortBy: 'createdAt',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', editable: false },
      { dataIndex: 'presentationNo', title: 'Presentation No.', editable: false },
      { dataIndex: 'vendorCode', title: 'Vendor Code', editable: false },
      { dataIndex: 'vendorName', title: 'Vendor Name', editable: false },
      { dataIndex: 'division', title: 'Division', editable: false },
      { dataIndex: 'subDivision', title: 'Sub Division', editable: false },
      { dataIndex: 'majorCategory', title: 'Major Category', editable: false },
      { dataIndex: 'presentationReceivedDate', title: 'Presentation Received', type: 'date', editable: false },
      { dataIndex: 'designNumber', title: 'Design Number', editable: false },
      { dataIndex: 'fabric', title: 'Fabric', editable: false },
      { dataIndex: 'noOfColors', title: 'No. of Colors', editable: false },
      { dataIndex: 'price', title: 'Price', align: 'right', editable: false },
      { dataIndex: 'imageUrl', title: 'Image URL', editable: false },
      { dataIndex: 'presentationsType', title: 'Presentation Type', editable: false },
      { dataIndex: 'uniqueKey', title: 'Unique Key', editable: false },
      { dataIndex: 'source', title: 'Source', editable: false },
      { dataIndex: 'status', title: 'Status', editable: false },
      { dataIndex: 'retryCount', title: 'Retry Count', editable: false },
      { dataIndex: 'errorMessage', title: 'Error Message', editable: false },
      { dataIndex: 'extractedAt', title: 'Extracted At', type: 'date', editable: false },
      { dataIndex: 'flatId', title: 'Flat ID', editable: false },
      { dataIndex: 'lockedUntil', title: 'Locked Until', type: 'date', editable: false },
      { dataIndex: 'articleNumber', title: 'Article Number', editable: false },
      { dataIndex: 'createdAt', title: 'Created At', type: 'date', editable: false },
      { dataIndex: 'updatedAt', title: 'Updated At', type: 'date', editable: false },
    ],
  },
  'vendor-master': {
    title: 'Vendor Master (DAB Sync)',
    description: 'All rows currently stored in master_vendor_details. Read-only — synced automatically from the DAB vendor master, so edits here would just be overwritten by the next sync.',
    rowKey: 'id',
    defaultSortBy: 'syncedAt',
    defaultSortDir: 'desc',
    columns: [
      { dataIndex: 'id', title: 'ID', editable: false },
      { dataIndex: 'vendorCode', title: 'Vendor Code', editable: false },
      { dataIndex: 'vendorName', title: 'Vendor Name', editable: false },
      { dataIndex: 'vendorCity', title: 'Vendor City', editable: false },
      { dataIndex: 'vendorRegion', title: 'Vendor Region', editable: false },
      { dataIndex: 'mergeVendorCode', title: 'Merge Vendor Code', editable: false },
      { dataIndex: 'mergeVendorName', title: 'Merge Vendor Name', editable: false },
      { dataIndex: 'mergeVendorCity', title: 'Merge Vendor City', editable: false },
      { dataIndex: 'mergeVendorRegion', title: 'Merge Vendor Region', editable: false },
      { dataIndex: 'syncedAt', title: 'Synced At', type: 'date', editable: false },
    ],
  },
};
